/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributioncenter;

import java.awt.event.KeyEvent;
import java.io.*;
import java.util.ArrayList;
import java.util.List;

import java.util.Scanner;
import javax.swing.JOptionPane;


/**
 *
 * @author admin
 */
public class Stock_1 extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnPackage = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jTextFieldOut = new javax.swing.JTextField();
        DailyOut = new javax.swing.JLabel();
        jBtnAdd = new javax.swing.JButton();
        jTextFieldIn = new javax.swing.JTextField();
        DailyIn = new javax.swing.JLabel();
        cbItem = new javax.swing.JComboBox<String>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 350));
        setSize(new java.awt.Dimension(450, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 0, 415, -1));

        jBtnPackage.setBackground(new java.awt.Color(0, 102, 153));
        jBtnPackage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnPackage.setText("Total Package in Stock");
        jBtnPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPackageActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 240, -1));

        jBtnExit.setBackground(new java.awt.Color(0, 102, 153));
        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 75, -1));

        jBtnDelete.setBackground(new java.awt.Color(0, 102, 153));
        jBtnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnDelete.setText("Delete");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, 20));
        getContentPane().add(jTextFieldOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 50, -1));

        DailyOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DailyOut.setText("Daily Package Out:");
        getContentPane().add(DailyOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jBtnAdd.setBackground(new java.awt.Color(0, 102, 153));
        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 75, 20));

        jTextFieldIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInActionPerformed(evt);
            }
        });
        jTextFieldIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldInKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 50, -1));

        DailyIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DailyIn.setText("Daily Package in:");
        getContentPane().add(DailyIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        cbItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an item" }));
        cbItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbItemActionPerformed(evt);
            }
        });
        getContentPane().add(cbItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 194, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stock");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Item in Stock:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 107, 110, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbItemActionPerformed
        // TODO add your handling code here:
        try{
            Scanner input = new Scanner(new File("Item.txt"));
            input.useDelimiter(",|\n"); 
            while(input.hasNext()){
                String itemCategory = input.next();
                String itemDescription=input.next();
                String itemBarcode=input.next();
                String itemQty=input.next();
                String itemCostPrice=input.next();
                String sanitized = itemCostPrice.replaceAll("\\s+","");
                
                Item item = new Item(itemCategory,itemDescription,itemBarcode,Integer.valueOf(itemQty),Integer.valueOf(sanitized));
                
                if(item.getItemDescription().equalsIgnoreCase(String.valueOf(cbItem.getSelectedItem()))){
                    JOptionPane.showMessageDialog(null, item.getItemDescription()+ " quantity is : "+ item.getItemQty());
                    break;
                }
                
               
            }
        }
        catch(IOException io){
            JOptionPane.showMessageDialog(null,"File not found.");
        }
    }//GEN-LAST:event_cbItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       try{
      
            Scanner sc = new Scanner(new File("item.txt"));
            String newLine = System.getProperty("line.separator");
            while (sc.hasNextLine()){
                String[] words = sc.nextLine().split(",");
                cbItem.addItem(words[1]);
            }
            
        }
        catch(IOException io){
            JOptionPane.showMessageDialog(null,"File not found.");
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void jTextFieldInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInActionPerformed
private static final String FILE_PATH = "Stock.txt";
    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
         String In =jTextFieldIn.getText();
        
        try{   FileWriter fw = new FileWriter(FILE_PATH,true);
               BufferedWriter bw = new BufferedWriter(fw);
               
              
               fw.write(In +"\n");
           
            
            fw.close();
            JOptionPane.showMessageDialog(null, "item saved successfuly", "SAVE ITEM",JOptionPane.INFORMATION_MESSAGE);
    }
    catch(Exception e){
    }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private int getPackageNum (){
         try{
            FileInputStream itemFile = new FileInputStream(FILE_PATH);
            InputStreamReader iSReader = new InputStreamReader(itemFile);
            BufferedReader buffReader = new BufferedReader(iSReader);

            List<String> itemDetails = new ArrayList<>(10);
            String line;
            while ( (line = buffReader.readLine()) != null) {
                itemDetails.add(line);

            }
        
            buffReader.close();
            iSReader.close();
            itemFile.close();

            int sum = 0;
            for(String num : itemDetails){

                if(num.length() > 0)
                    sum+= Integer.parseInt(num);
            }
                
        
            return sum;
        } 
        catch (IOException e) {
            System.out.println("Didn't run");
            e.printStackTrace();
        }
         return -1;
    }
    
    private void jBtnPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPackageActionPerformed
       
       try{
           
       JOptionPane.showMessageDialog(null, "The total package in stock is:"+ getRemainingStock ());
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "The total package in stock is:"+ getPackageNum ());
       }
    }//GEN-LAST:event_jBtnPackageActionPerformed

    private void jTextFieldInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInKeyTyped
      
    }//GEN-LAST:event_jTextFieldInKeyTyped

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        this.setVisible(false);
        
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
     
     
     Stock_In si = new Stock_In();
     String numOut= jTextFieldOut.getText();
     int out= Integer.parseInt(numOut);
     
      JOptionPane.showMessageDialog(null, "Number of packages removed is:"+ si.getPackageOut(out));
     
    }//GEN-LAST:event_jBtnDeleteActionPerformed
      
        public int getRemainingStock (){
            Stock_In si = new Stock_In();
           int packageNum = this.getPackageNum();
           String numOut= jTextFieldOut.getText();
           int out= Integer.parseInt(numOut);
           int packageOut = si.getPackageOut(out);
           int delete=(packageNum-packageOut);
           return delete;
           
       }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DailyIn;
    private javax.swing.JLabel DailyOut;
    private javax.swing.JComboBox<String> cbItem;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnPackage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldIn;
    private javax.swing.JTextField jTextFieldOut;
    // End of variables declaration//GEN-END:variables
}
